version: '3.7'

services:
  db:
    image: postgres:13-alpine
    volumes:
      # - ./data:/var/lib/postgresql/data
      - /path/on/host:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_NAME=${NAME}
  #     - DB_USER=${USER}
  #     - DB_PASS=${PASSWORD}
  app:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - .:/app  

    command: sh -c "pip install djangorestframework-simplejwt && python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    ports:
        - 8000:8000

    environment:
        - DB_HOST=db
        - DB_NAME=${NAME}
        - DB_USER=${USER}
        - DB_PASS=${PASSWORD}
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
