# Generated by Django 3.2.20 on 2023-07-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('title_image', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('content_title', models.CharField(max_length=255)),
                ('content_description', models.TextField()),
                ('content_image_url', models.URLField(max_length=1000)),
                ('content_image_source', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('section_content', models.TextField()),
                ('section_link', models.URLField(max_length=1000)),
                ('section_image', models.URLField(max_length=1000)),
                ('section_image_source', models.CharField(max_length=500)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='article.article')),
            ],
        ),
    ]
