# Generated by Django 3.2.20 on 2023-07-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('title_image_url', models.URLField(max_length=1000)),
                ('date', models.DateField()),
                ('sum_title', models.CharField(max_length=50)),
                ('sum_description', models.TextField()),
                ('sum_image_url', models.URLField(max_length=1000)),
                ('sum_imageSource_description', models.CharField(max_length=50)),
                ('sum_image_source_url', models.URLField(max_length=1000)),
                ('section_1_title', models.CharField(max_length=50)),
                ('section_1_content', models.TextField()),
                ('section_1_extended_reading_title', models.CharField(max_length=50)),
                ('section_1_extended_reading_link', models.URLField(max_length=1000)),
                ('section_1_image', models.URLField(max_length=1000)),
                ('section_1_imageSource_description', models.CharField(max_length=1000)),
                ('section_1_image_link', models.URLField(max_length=1000)),
                ('section_2_title', models.CharField(max_length=50)),
                ('section_2_content', models.TextField()),
                ('section_2_extended_reading_title', models.CharField(max_length=50)),
                ('section_2_extended_reading_link', models.URLField(max_length=1000)),
                ('section_2_image', models.URLField(max_length=1000)),
                ('section_2_imageSource_description', models.CharField(max_length=1000)),
                ('section_2_image_link', models.URLField(max_length=1000)),
                ('section_3_title', models.CharField(max_length=50)),
                ('section_3_content', models.TextField()),
                ('section_3_extended_reading_title', models.CharField(max_length=50)),
                ('section_3_extended_reading_link', models.URLField(max_length=1000)),
                ('section_3_image', models.URLField(max_length=1000)),
                ('section_3_imageSource_description', models.CharField(max_length=1000)),
                ('section_3_image_link', models.URLField(max_length=1000)),
            ],
        ),
    ]
